[versions]
agp = "8.9.1"
kotlin = "2.1.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"
hilt = "2.57.2"
hiltExt = "1.3.0"
androidxNavigation = "2.9.6"
androidxHiltNavigationCompose = "1.3.0"
kotlinxCoroutines = "1.10.2"
#kotlinKsp = "1.9.0-1.0.12"
kotlinKsp = "2.1.0-1.0.29"
serialization = "2.3.0"
ktorClient = "3.3.3"
ktorClientCio = "3.3.3"
kotlinxSerialization = "1.9.0"
liveData = "1.10.0"
lifecycle-compose = "2.10.0"
coilVersion = "2.7.0"
compose = "1.6.7"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

#Navigation Compose
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref="androidxNavigation"}

#Dependency injection
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }

#kotlinx serialization
kotlinx-serialization = { group ="org.jetbrains.kotlinx", name ="kotlinx-serialization-json", version.ref="kotlinxSerialization"}

#coil
coil-compose = { group = "io.coil-kt", name ="coil-compose", version.ref = "coilVersion"}

#compose lifecycle
runtime-livedata = { group ="androidx.compose.runtime", name ="runtime-livedata", version.ref="liveData"}
lifecycle-compose = { group ="androidx.lifecycle", name ="lifecycle-viewmodel-compose", version.ref="lifecycle-compose"}

#Ktor client
kotlinx-coroutines = { group ="org.jetbrains.kotlinx", name ="kotlinx-coroutines-core", version.ref="kotlinxCoroutines"}
client-android = { group ="io.ktor", name ="ktor-client-android", version.ref="ktorClient"}
client-serialization = { group ="io.ktor", name ="ktor-client-serialization", version.ref="ktorClient"}
client-logging = { group ="io.ktor", name ="ktor-client-logging", version.ref="ktorClient"}
client-auth = { group ="io.ktor", name ="ktor-client-auth", version.ref="ktorClient"}
client-content-negotiation = { group ="io.ktor", name ="ktor-client-content-negotiation", version.ref="ktorClient"}
ktor-serialization = { group ="io.ktor", name ="ktor-serialization-kotlinx-json", version.ref="ktorClient"}
client-cio = { group ="io.ktor", name ="ktor-client-cio", version.ref="ktorClientCio"}


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsKotlinKsp = { id = "com.google.devtools.ksp", version.ref = "kotlinKsp" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
#kotlinxSerialization = {id = "kotlinx-serialization"}
hiltPlugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

